// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc3U1FFyde8qol8rbn3KXf3WyY_XtqMEQ',
    appId: '1:803291695196:web:fb2884df89e81b6ae3be99',
    messagingSenderId: '803291695196',
    projectId: 'gallery-9c4a3',
    authDomain: 'gallery-9c4a3.firebaseapp.com',
    storageBucket: 'gallery-9c4a3.appspot.com',
    measurementId: 'G-FGXEWWRFCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCipo3KdFCelEMx0-YJuDa7VbgKkC_4tTs',
    appId: '1:803291695196:android:49b391208a8231d1e3be99',
    messagingSenderId: '803291695196',
    projectId: 'gallery-9c4a3',
    storageBucket: 'gallery-9c4a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOr2fPdG0UtLud2bpOII-Qkv3O8pxxn8A',
    appId: '1:803291695196:ios:380e639742f5a125e3be99',
    messagingSenderId: '803291695196',
    projectId: 'gallery-9c4a3',
    storageBucket: 'gallery-9c4a3.appspot.com',
    iosBundleId: 'com.example.galleryAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOr2fPdG0UtLud2bpOII-Qkv3O8pxxn8A',
    appId: '1:803291695196:ios:2f03908db940ee5be3be99',
    messagingSenderId: '803291695196',
    projectId: 'gallery-9c4a3',
    storageBucket: 'gallery-9c4a3.appspot.com',
    iosBundleId: 'com.example.galleryAppFlutter.RunnerTests',
  );
}
